import ReduxProvider from "@/components/redux-provider"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" bg-[#FDFDFD] w-[100vw] h-[100vh]">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
